---
- include: newrelic-apt.yml
  when: provision_new_relic|default(False)|bool and (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')
  tags: [ provision ]

- name: Install New Relic SysMonD
  package:
    name: newrelic-sysmond
    state: latest
    use: apt
  notify:
    - Restart New Relic sysmond
  tags: [ provision ]

- include: newrelic-sysmond.yml
  when: newrelic_license_key|default(False) != False
  notify:
    - Restart New Relic sysmond

- name: Is PHP-FPM installed?
  stat:
    path: '{{ newrelic_php_etc_base }}/fpm/php.ini'
  register: php_fpm_ini

- name: Install PHP Agent if PHP-FPM is installed
  package:
    name: "newrelic-php5"
    state: latest
    use: apt
  when: php_fpm_ini.stat.exists
  notify: 'Restart php-fpm'
