---
- name: Add New Relic APT key
  apt_key:
    url: 'https://download.newrelic.com/548C16BF.gpg'
    id: 548C16BF
    state: present

- name: Add New Relic APT repository
  apt_repository: 
    repo: 'deb http://apt.newrelic.com/debian/ newrelic non-free' 
    state: present
    update_cache: yes
