---
- name: RedHat | Set newrelic_loaded_os_family
  set_fact:
    newrelic_loaded_os_family: "{{ ansible_os_family }}"

- name: RedHat | Add the New Relic repository key
  copy:
    src: RPM-GPG-KEY-NewRelic
    dest: /etc/pki/rpm-gpg
    owner: root
    group: root
    mode: 0644
  sudo: yes

- name: RedHat | Add the Rew Relic repository file
  copy:
    src: newrelic.repo
    dest: /etc/yum.repos.d/newrelic.repo
    owner: root
    group: root
    mode: 0644
  sudo: yes

- name: RedHat | Install New Relic Sysmond
  yum:
    name: newrelic-sysmond
    state: latest
  sudo: yes
  notify:
    - Restart New Relic

- name: RedHat | Install New Relic PHP5 agent
  yum:
    name: newrelic-php5
    state: latest
  sudo: yes
  notify:
    - Restart New Relic
    