---
# handlers file for drupsible.newrelic
- name: Restart php-fpm
  service:
    name: "php{{ newrelic_php_version }}-fpm"
    state: restarted
  ignore_errors: True

- name: Restart New Relic sysmond
  service:
    name: newrelic-sysmond
    state: restarted
